const CALENDAR_EVENT_TRACKER_NAME = `calendar-event-tracker`;
const CALENDAR_EVENT_TRACKER_EDITOR_NAME = `${CALENDAR_EVENT_TRACKER_NAME}-editor`;

export {
  CALENDAR_EVENT_TRACKER_NAME,
  CALENDAR_EVENT_TRACKER_EDITOR_NAME
};
